# Generated by Django 5.0 on 2024-01-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clerk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clerk_id", models.CharField(max_length=50)),
                (
                    "clerk_account",
                    models.CharField(default="default", max_length=50, null=True),
                ),
                (
                    "clerk_name",
                    models.CharField(default="default", max_length=50, null=True),
                ),
                ("clerk_phone_num", models.CharField(max_length=50, null=True)),
                ("clerk_change", models.FloatField(default=0, null=True)),
                ("clerk_register_time", models.DateTimeField(null=True)),
                ("clerk_email", models.CharField(max_length=50, null=True)),
                ("clerk_update_time", models.DateTimeField(null=True)),
                ("clerk_status", models.BooleanField(default=False, null=True)),
                ("clerk_register", models.BooleanField(default=False)),
                ("del_flag", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dev_id", models.CharField(max_length=50)),
                ("dev_user_id", models.CharField(max_length=50, null=True)),
                ("dev_address", models.CharField(max_length=50, null=True)),
                ("dev_height", models.FloatField(null=True)),
                ("dev_battery", models.FloatField(null=True)),
                ("dev_create_time", models.DateTimeField(null=True)),
                ("dev_update_time", models.DateTimeField(null=True)),
                ("dev_duration", models.IntegerField(default=0, null=True)),
                ("dev_status", models.IntegerField(null=True)),
                ("del_flag", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50)),
                ("order_user_id", models.CharField(max_length=50)),
                ("order_clerk_id", models.CharField(max_length=50, null=True)),
                ("order_tag", models.BooleanField(null=True)),
                ("order_price", models.FloatField(null=True)),
                ("order_status", models.IntegerField(null=True)),
                ("order_memo", models.CharField(max_length=100, null=True)),
                ("order_address", models.CharField(max_length=50, null=True)),
                ("order_create_time", models.DateTimeField(null=True)),
                ("order_update_time", models.DateTimeField(null=True)),
                ("order_finish_time", models.DateTimeField(null=True)),
                ("order_remark", models.IntegerField(default=0, null=True)),
                ("del_flag", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Repair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repair_id", models.CharField(max_length=50, null=True)),
                ("repair_user_id", models.CharField(max_length=50, null=True)),
                ("repair_memo", models.CharField(max_length=100, null=True)),
                ("repair_status", models.IntegerField(default=0)),
                ("repair_photo", models.CharField(max_length=100, null=True)),
                ("repair_create_time", models.DateTimeField(null=True)),
                ("del_flag", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50)),
                (
                    "user_district",
                    models.CharField(default="default", max_length=50, null=True),
                ),
                (
                    "user_address",
                    models.CharField(default="default", max_length=50, null=True),
                ),
                (
                    "user_account",
                    models.CharField(default="default", max_length=50, null=True),
                ),
                ("user_change", models.FloatField(default=0, null=True)),
                ("user_credit", models.FloatField(default=0, null=True)),
                ("phone_num", models.CharField(max_length=50, null=True)),
                ("dev_id", models.CharField(max_length=50, null=True)),
                ("register_time", models.DateTimeField(null=True)),
                ("isRegister", models.BooleanField(default=False)),
                ("user_status", models.IntegerField(default=0, null=True)),
                ("del_flag", models.BooleanField(default=False)),
            ],
        ),
    ]
